version: '3.8'

services:
  synergos:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - PORT=8080
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/get_api_key_status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - synergos-network

networks:
  synergos-network:
    driver: bridge